### ISSUE TITLE
SearchById not working

### ISSUE THREAD

**Issue by remware** [FirelyTeam/fhir-net-api#1079]
Hi,
we tried several samples codes with r4/develop server and develop-r4 client. Last one was looking like this:
var incl = new string[] { "Appointment.participant" };
Bundle results = client.SearchById<Appointment>("1", incl);

where rendered url was:
http://localhost:5011/fhir/Appointment?_include=Appointment.participant&_id=1
and returned bundle was empty.

So we tried in kufu server as in http://spark.kufu.no/fhir/Patient/238
with code 
bundle results = client.SearchById<Patient>("1");
that rendered correctly
http://spark.kufu.no/fhir/Patient?_id=238
and returned a search set
Type: Searchset, 1 of 1
Patient/238/_history/1
but not the resource itself to class Patient
http://spark.kufu.no/fhir/Patient/238

After digging on running code I noticed that for _id criteria is adding fhir_id and mongo does not understand that. Similarly for internal_resource I see resource in mongo. Is the fhir client and server syncronized?

How should search be used?

**Comment by ewoutkramer** [comment]
Hi @remware,

You are using the `SearchById` incorrectly.  The first parameter is the resource name, but it seems you are passing in the identifier instead.   In fact, your code should not have compiled because of this.  

If you are tring to find Appointment with id "1", you should be doing:

```
    var result = client.SearchById("Appointment", "1");
```

Also, although Appointment DOES have an element "paticipant", FHIR _only_ lets you include related resources that are expressed as a search parameter (http://hl7.org/fhir/appointment.html#search), see here: http://hl7.org/fhir/appointment.html#search.

In this case, I guess you actually want Appointment.participant.actor, which can be done like this:

```
    var incl = new string[] { "Appointment:actor" };
    Bundle results = client.SearchById("Appointment", "1", incl);
```

Also, not the ":" in the included string, instead of ".".

Hope that helps.
