### ISSUE TITLE
Unhandled exception on any HTTP request missing fhir mimeType

### ISSUE THREAD

**Issue by znatty22** [FirelyTeam/fhir-net-api#1164]
Platform(s)
---------
Docker images: `simplifier/vonk:3.0.0-beta2`

Issue
------
Any request that is missing the `fhirVersion` mimeType in either `Accept` or `Content-Type` header results in an unhandled exception on the Vonk server. This issue affects vonkloader which does not seem to set these headers by default. Thus, its not possible to use the vonkloader with this version of Vonk.

Example with response:
![image](https://user-images.githubusercontent.com/10283712/67883241-1f0a4900-fb1a-11e9-8f88-f5f6d04411b0.png)

Expected Behavior
--------------------
Option 1: If the `fhirVersion` mimeType isn't specified default to STU3 
Option 2: The server should respond more gracefully with an error message stating that the `fhirVersion` mimeType is missing along with a 400 status code to indicate client error.

I realize in release 3.0.0 the InformationModel server setting has been introduced so requests don't have to include the mimeType but I thought it would still be useful to report this in case the team wants to note it on the simplifier docs site for Vonk.

Vonk Stack Trace
------------------
[stacktrace.txt](https://github.com/FirelyTeam/fhir-net-api/files/3790404/stacktrace.txt)

**Comment by marcovisserFurore** [comment]
Hi Natasha,

Thank you for your issue, but unfortunately at the wrong project. This project is about the Fhir .Net Api, which is used by Vonk and many other products. Your issue is related to Vonk. 
But you are lucky, because I am also working on Vonk as a developer ;)

You are right: in Vonk version 3.0.0-beta2 this happend when you not added the FhirVersion. We solved this issue by falling back to a FhirVersion default, which can be configured in the InformationModel settings in Vonk. See [here](http://docs.simplifier.net/vonk/configuration/appsettings.html#information-model) for more documentation about this setting.

I advise you to use Vonk version 3.0.0 and not use any beta version anymore.

**Comment by znatty22** [comment]
Ok sounds good @marcovisserFurore, thank you!
