### ISSUE TITLE
Requests from a browser to Vonk result in wrong Content-Type in response

### ISSUE THREAD

**Issue by znatty22** [FirelyTeam/fhir-net-api#1165]
Issue
------
The FHIR spec states: 
```
If a client provides a generic mime type in the Accept header (application/xml, text/json, or application/json), the server SHOULD respond with the requested mime type, using the XML or JSON formats described in this specification as the best representation for the named mime type (except for binary - see the note on the Binary resource).
``` 
https://www.hl7.org/fhir/http.html

Sending requests to the Vonk server via the browser results in a file download because the Content-Type in the response header is something the browser doesn't recognize (`application/fhir+xml`)

Expected Behavior
-------------------
Respond with standard mimeType in Content-Type response header so that the browser can display it rather than download a file

Details
-------------
![image](https://user-images.githubusercontent.com/10283712/67888149-018dad00-fb23-11e9-8405-987b325755ee.png)

**Comment by marcovisserFurore** [comment]
Hi Natasha,

Thanks for the issue, This issue is about the product Vonk and not about this project Fhir .Net Api. Vonk uses this Api. But as a Vonk developer also, I can answer your issue as well.

The standard states that when you provide a generic accept header, like `application/xml` or `text/json`,  the server should understand this and convert it to Fhir mime type, so `application/fhir+xml` and `application/fhir+json`. 
In the capabilitystatement (https://vonk.fire.ly/metadata) is stated which formats the server supports. Vonk supports only `xml` and `json`. So you are accepting `text/html`, `application/xhtlm+xml` and `application/xml` in your rewuest, Vonk understands only `application/fhir+xml` and converts the mime type to it.  

For more support questions or issues you can send an email to vonk@fire.ly.

**Comment by znatty22** [comment]
Hi @marcovisserFurore thanks for your quick reply! Hmm I guess I misread the spec. I thought it was saying if a client provides a generic mime type in the Accept header, then the server should respond with that mimeType.

Wrt to Vonk issues, do you know if there is another repository or a better place to submit issues or feature requests?

**Comment by marcovisserFurore** [comment]
Hi Natasha, 
Vonk is a commercial product and comes with a license. When you have a paid license, you automatically also have support on the product. For more information about Vonk and prices, see our web page https://fire.ly/products/vonk/. 

General remarks or issues can be sent at vonk@fire.ly
