### ISSUE TITLE
Questions Regarding Partial Classes & The Simplifier Documentation

### ISSUE THREAD

**Issue by ps-jeremykato** [FirelyTeam/fhir-net-api#1178]
Hi Firely Team:

In [one of the Simplifier documentation](http://docs.simplifier.net/fhirnetapi/model/classes.html) pages, our team noticed that the following was included:

> For each Resource type and data type in FHIR, the API contains a class in the form of a public partial class. If you need extra code to be performed when using these classes, you can just implement your own partial class for it. That way you can keep your code separate from the API code.

However, according to the C# documentation, [partial classes must exist within the same assembly](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods):

> All partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions cannot span multiple modules.

Is there a way to implement partial classes without forking the repository and adding the code there, or is there any other information that we're missing?

**Comment by cknaap** [comment]
This instruction is indeed targeted towards developers having their own fork of the API, since you cannot work around the limitation of .NET that you already mentioned: the partial classes must be in the same assembly.
Using the partial classes just isolates you from the regeneration of the POCO classes from the specification that happens for new versions of FHIR.
