### ISSUE TITLE
Use of profiled datatypes within a SD results in invalid snapshot

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/fhir-net-api#1303]
Generating a snapshot using Simplifier or Vonk (3.3 / 3.4) of one of the following profile will create invalid results:
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.laborbefund/0.9.0/files/114053/~json
https://simplifier.net/nictizstu3-zib2017/nl-core-patient

Some elements will be assigned a "max" of "*" whereas max is greater than base.max of "1". This should not be the case as it is not allowed.
The element DiagnosticReport.identifier:befund.assigner is generated incorrect in the german profile.
The elements Patient.name and Patient.address are generated incorrect in the Nictiz profile. 

The error seems to be in the snapshot generator. Downloading the snapshot from Simplifier shows the error in cardinality. While the diff is correct.

-  It seems to be caused by use of profiled datatype within a StructureDefinition.
-  The StructreDefinition XML seems ok. Doens’t violate the base. Seems to be an error in the snapshot.
-  Forge renders the 0..* as well. Instead of the base 0..*
-  The Simplifier validator seems to be ok with sending more than the base cardinality should allow. 
-    Another thing that is remarkable and maybe the cause of this, is that the root elements have cardinalities of 0..* as well. Perhaps by adding a profiled datatype, the root element is used for the cardinality.

**Comment by ewoutkramer** [comment]
Related to #1108 ?

**Comment by ewoutkramer** [comment]
Yes - this is all consistent and all about the same issue. There's simply no computable rule/invariant in the FHIR spec that would trigger validation warnings about this. But the core of the issue is that there are several inconsistent cardinalities in play: the one coming from the base and the one in the profile. For cardinality, it seems to make sense to take the "lowest" value of the two, but for other constraints, it is not so easy - or impossible.  I'll take a look at solving this at least for the cardinality.
