### ISSUE TITLE
Are all valid FHIR paths supported?

### ISSUE THREAD

**Issue by moria97** [FirelyTeam/fhir-net-api#1321]
I compared the source code and the [FHIRPath documents.](http://hl7.org/fhirpath/). Seems that some FHIRPath functions like exclude(), toBoolean()...
I wander whether all standard FHIRPaths have been supported in this library?
Thanks!

**Comment by ewoutkramer** [comment]
No, the current 1.x versions of the API do not support all the functions from the recently published Normative edition of FhirPath.  We can only do this in the 2.x release, since some of these changes are not backwards-compatible.  I have worked on `toBoolean()` in the 2.x release, so I know that one will be included.

Fortunately, you can -for now- add your own implementations of these functions - the compiler takes a SymbolTable argument that you can initialize with your own implementations. Take a look at the library's code here, here you can see how we add the currently supported functions. It's quite easy to add your own:

https://github.com/FirelyTeam/fhir-net-common/blob/develop/src/Hl7.FhirPath/FhirPath/Expressions/SymbolTableInit.cs

**Comment by moria97** [comment]
Thanks! The function extension is really helpful.
