### ISSUE TITLE
JSON Parser throws 'Encountered unknown element'

### ISSUE THREAD

**Issue by daniloacim** [FirelyTeam/fhir-net-api#1503]
Hello,

I'm trying to parse JSON data using Hl7.Fhir.Serialization.FhirJsonParser.
The data can be found on the following link: [https://confluence.hl7.org/display/COD/mCODE+Test+Data](https://confluence.hl7.org/display/COD/mCODE+Test+Data) under https://mcodeapp.org/testdata/mcode1_0_10yrs.zip

The Parser constantly throws the following error: Encountered unknown element '{name of the property}'

For example, for observations it throws: 
                          **Encountered unknown element 'encounter' 
                          Encountered unknown element 'reference' in performer
			  Encountered unknown element 'category'** 

Checked the FHIR specification and these properties exist by the specification.

Removed all entities from the JSON except Patient and it works fine. Seems there are some problems in Observation, Encounter, DiagnosticReport... entities. There are a lot of fields that can not be parsed.

The parser belongs to the: **Assembly Hl7.Fhir.STU3.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3**

Do you know what could be a problem?

**Comment by ewoutkramer** [comment]
For now, I have to assume it is something in your code, since this is a well-travelled codepath.  Can you show me how you call the library and point to a specific file that fails?

(this seems to be about Json -- if there's any XML in play here, most of the time this means a missing/incorrect namespace declaration)

**Comment by mbaltus** [comment]
These kind of errors usually indicate a version mismatch. Looking at the data you provided, I do notice some R4 specific extensions in your data, most notably the patient-birthPlace one. Also, when I validate, I get an error on Observation.encounter, which is a field that was renamed from context to encounter in R4.
I think your parser problems will disappear if you would add the R4 library (Hl7.Fhir.R4.Core) instead of the STU3 one you are using now.

**Comment by daniloacim** [comment]
The version caused the problem.
I need to use Hl7.Fhir.R4.Core. 

Thank you!

**Comment by mbaltus** [comment]
You're welcome!
