### ISSUE TITLE
Type checking the data literal

### ISSUE THREAD

**Issue by kfrancis** [FirelyTeam/fhir-net-api#1510]
Having an issue with the following:

```
...
"valueTime": "100525",
...
```

Getting the error: Hl7.Fhir.ElementModel.StructuralTypeException : Type checking the data: Literal '100525' cannot be parsed as a time. (at Bundle.entry[0].resource[0].contained[40].valueTime[0])

What are my options here? Is there some way I can specify the format or adjust the parsing implementation?

**Comment by marcovisserFurore** [comment]
Hi @kfrancis. 

Thanks for using our product. 
I think you are parsing here a Json file, and this file contains an attribute `valueTime`. The Api tries to parse this to the datatype [time](https://www.hl7.org/fhir/datatypes.html#time). According to the Fhir standard the datatype time must confirm to the following regex `([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?`.

Your value is `100525` which does not conform to the described regex. That's why the Api cannot parse this value. The value should be something like this `10:05:25`. 
So adjusting the value the right format, will solve this parsing error.

**Comment by kfrancis** [comment]
We're calling a federal rest service which is returning json, yes. I've already had to make corrections to the response for things like deceasedDate (which is really a deceasedDateTime), I just don't understand why there are issues like this when they are stating it's a "standard" STU3 being used.

**Comment by marcovisserFurore** [comment]
Can it be that you are using a different FHIR version than the federal rest service is using? Although, I think you are talking about  `deceasedDateTime` of a `Patient`, which has been since version DSTU2 unchanged. So for STU3 it is also `deceasedDateTime` and not `deceasedDate`.

**Comment by kfrancis** [comment]
It's listed as STU3 for messaging: https://simplifier.net/guide/OntarioLaboratoriesInformationSystemProviderQuery/Introduction

![msedge_TYbJPgJ9IV](https://user-images.githubusercontent.com/67574/95224693-fd551f80-07c8-11eb-994c-5c3b8b01192d.png)

I'm using Hl7.FHIR.STU3 v2.0.0 beta-2 (I needed to move to this version so I could modify the response body before parsing took place and also to make testing easier).

**Comment by marcovisserFurore** [comment]
Ah, you are using cutting edge beta technology ;)

I looked into the implementation guide and I cannot find strange things. I cannot test it myself (I think), because the server is secured by OAuth2. 

The only thing I am thinking of, is that probably the `FhirClient` is not doing well in beta2. I don't really think so, because we have a lot of unit tests which prove it works. Is it perhaps  possible to test it with the 1.9 version of the `FhirClient`? If you still have the same problem in 1.9, then it is definitely not the beta2 implementation. If it does work in 1.9, our api team has to come up with a fix for this.

**Comment by kfrancis** [comment]
Same thing in 1.9, I just don't get the opportunity to correct it then.

I have a working way to correct it now, I was just more curious is there was a way I could intercept these types of issues in a more standardized way then ultimately string processing:

```c#
if (responseBody.Contains("valueTime"))
{
    int adjustedIndex = 0;
    foreach (var index in responseBody.AllIndexesOf("valueTime"))
    {
        var timeValue = responseBody.Substring(index + adjustedIndex + 12, 6);
        if (!timeValue.Contains(":") && timeValue.Length == 6)
        {
            var updatedTimeValue = timeValue.Insert(2, ":").Insert(5, ":");
            responseBody = responseBody.Remove(index + adjustedIndex + 12, 6).Insert(index + adjustedIndex + 12, updatedTimeValue);
            responseModified = true;
            adjustedIndex += updatedTimeValue.Length - timeValue.Length;
        }
    }
}
```

**Comment by marcovisserFurore** [comment]
Ah okay, happily for us is not a beta2 problem. :)

But, it is still not okay. The response that you receive should not be corrected. If all clients have to do this, then why we have a standard? I would advise you to contact the eHealth Ontario and explain them your troubles with the response that you get.

**Comment by ewoutkramer** [comment]
Is it possible to send a piece of this data for us to double check (as long as this is test data, otherwise, please don't)

**Comment by kfrancis** [comment]
@ewoutkramer I'm checking on that. It is test data, but I just want to double-check with eHealth Ontario.

**Comment by kfrancis** [comment]
Here's the example related to this case where valueTime is wrong:

[example.log](https://github.com/FirelyTeam/fhir-net-api/files/5335933/example.log)

As this is just a testing environment, they say that it's fine but they also note the following: 

> Regarding the “valueTime” in FHIR mesg, as per OLIS Specification, Time is always represented as:  HHMMSS+/-ZZZZ; and Dates are always represented as CCYYMMDD; so for example, 12:30pm EST on November 4th, 2006 would be represented as: 20061104123000-0500.

> As such  “100525” is the correct format for observation data type “TM” while “10:05:25” is an invalid one.

**Comment by brianpos** [comment]
TM isn't a FHIR datatype, sounds like they are mixing their standards, and do note that they don't even point out on their implementation page that this should be on how they do time only fields, but the do explicitly point out date and datetime values
https://simplifier.net/guide/OntarioLaboratoriesInformationSystemProviderQuery/ImplementationConsideration
I do believe that this is a bug on their side. 
(and good to see that you're handling the fix in case they resolve it in the future like they should)

**Comment by kfrancis** [comment]
Thanks everyone for the help!
