### ISSUE TITLE
Base CachedResolver on .NET ObjectCache

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#411]
Just found this class: https://msdn.microsoft.com/en-us/library/system.runtime.caching.objectcache(v=vs.110).aspx, might be a nice base to implement CachedResolver on, since it provides cache dependencies and sliding updates etc. out of the box.

**Comment by wmrutten** [comment]
Yes please!
+ built-in support for cache dependencies
+ built-in support for cache invalidation
+ built-in support for file system (& database) change notifications
+ supports limit on memory size - very hard to implement manually, since you don't know sizeof(T)

Note: the .NET Framework provides separate implementations for use in ASP.NET and desktop environments. The FHIR API should support both, i.e. use some sort of factory or injection.

**Comment by ewoutkramer** [comment]
I've rewritten Cache<K,T> in 2.0 to use ObjectCache.
