### ISSUE TITLE
Replace [Obsolete] HttpWebRequest with HttpClient

### ISSUE THREAD

**Issue by sodell** [FirelyTeam/fhir-net-api#480]
HttpWebRequest is now obsolete and does not support > TLS 1.0. Additionally, when using http from a Xamarin application, Xamarin only knows how to translate the HttpClient implementation into the native (ios or android) http calls, which allows the latest version of TLS. Without this change, any Xamarin app using this library interfacing with something that requires TLS > 1.0, will encounter a runtime exception.

**Comment by sodell** [comment]
A co-worker of mine is currently attempting to tackle this. Hopefully we can have an elegant solution soon to be able to contribute this fix back.

**Comment by brianpos** [comment]
Thanks, looming forward to reviewing the pull request.
Which branch are you working on?
Develop-stu3

**Comment by ewoutkramer** [comment]
Great, looking forward to your PR.

**Comment by Devereux-Henley** [comment]
It looks like replacing the HttpWebRequest code entirely will introduce API breakage in
- [Hl7.Fhir.Rest.AfterResponseEventArgs](https://github.com/ewoutkramer/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Rest/FhirClient.cs#L1155)
  - [System.Net.HttpWebResponse](https://msdn.microsoft.com/en-us/library/system.net.httpwebresponse(v=vs.110).aspx) -> [System.Net.HttpResponseMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httpresponsemessage(v=vs.118).aspx)
- [Hl7.Fhir.Rest.BeforeRequestEventArgs](https://github.com/ewoutkramer/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Rest/FhirClient.cs#L1143)
  - [System.Net.HttpWebRequest](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.110).aspx) -> [System.Net.HttpRequestMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessage(v=vs.118).aspx)

The options seem to me to either introduce the HttpClient changes in a major release, or to provide a separate FhirClient for those who want to use the new functionality in order to avoid a breaking API change. 

What are your opinions @brianpos @ewoutkramer?

**Comment by ewoutkramer** [comment]
Yes, agree.  There are a few more places where I do need to make a breaking change.  Another idea would be to first include the change in R4 (which is a major anyway), but I would not want R3 users to miss the boat. That may well be a bigger evil that a breaking interface.

**Comment by brianpos** [comment]
I would actually like to see that part of the API abstracted away entirely, with the default implementation using what we already have.
Reason I'd like to do it is so that I could use the FhirClient on a local installation, and remove the web calls entirely while offline...
(Haven't re-checked the code how nasty this would be - then could have a simple replacement to resolve issue, and swap for R4)

**Comment by Devereux-Henley** [comment]
Couple questions: 
- Should we allow [default headers](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.defaultrequestheaders(v=vs.118).aspx) to be configured with FhirClient? This seems more elegant than setting header fields like the Authorization header in BeforeRequest.
- Should we allow an implementation of [HttpMessageHandler](https://msdn.microsoft.com/en-us/library/system.net.http.httpmessagehandler(v=vs.118).aspx) to be passed in? Currently using an instance of [HttpClientHandler](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler(v=vs.118).aspx) that just sets `AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate`, but that might be a decent point for extension if folks wanted to override `HttpMessageHandler.SendAsync`.
- What kind of abstraction are you two looking for over [HttpRequestMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessage(v=vs.118).aspx) and [HttpResponseMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httpresponsemessage(v=vs.118).aspx)? The HttpClient/HttpRequestMessage/HttpResponseMessage classes don't have interfaces that could be exposed. Are you thinking of having wrapper classes with exposed interfaces, or just passing in something like a dictionary of headers that need to be set in BeforeRequest / examined in AfterResponse?

**Comment by ewoutkramer** [comment]
I now realize the new classes clearly have a totally new API (I never looked at them, being a server dev ;-)  But it seems they support the notion of a pipeline as we discussed in #478.   So I am afraid I am not yet qualified to answer here, since I don't know enough about HttpClient...yet..... What about you, @brianpos?

**Comment by ewoutkramer** [comment]
I have been thinking about this a bit.  I think this will cause a re-design of the internal of the FhirClient.  That's not a bad thing - in fact I think we should have the freedom to do some redesign.

This means that - for compatibility reasons - it is better to create a new class, say FhirWebClient, and keep both.  We could extract common functionality (DRY) into a baseclass for both or in extension methods, then [Obsolete] the original FhirClient and give everyone a comfortable upgrade path...

**Comment by ewoutkramer** [comment]
Now that I have read up on FhirClient:

> Couple questions:
> Should we allow default headers to be configured with FhirClient?

Yes.

> Should we allow an implementation of HttpMessageHandler to be passed in? 

Yes.

There is a separate PR (#496) that tries to nest processing on the stream, so e.g. to include encryption of the body.  Would it be possible to make a HttpMessageHandler do that - is it feasible to pass a manipulated body to an inner message handler?

**Comment by sodell** [comment]
Linking the associated PR that is now open: https://github.com/ewoutkramer/fhir-net-api/pull/507

**Comment by brianpos** [comment]
This would be preferable with the message handler

**Comment by Devereux-Henley** [comment]
It should be possible.

```csharp
public class CoolHandler : HttpClientHandler
{
   protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   {
      var stream = await requestMessage.Content.ReadAsStreamAsync();
      var newStream = MyCustomClass.MyRequestStreamTransformation(stream);
      requestMessage.Content = new StreamContent(newStream);
      
      var response = await base.SendAsync(requestMessage, cancellationToken);

      var responseStream = await response.Content.ReadAsStreamAsync();
      var newResponseStream = MyCustomClass.MyResponseStreamTransformation(responseStream);
      response.Content = new StreamContent(newResponseStream);
      return response;
   }
}
```

**Comment by ewoutkramer** [comment]
Ah, yes, and you could even abstract it away by creating your own HttpContent subclass and putting the encryption logic in there...

**Comment by brianpos** [comment]
Unit testing with aspnetcore would also be easier, as it can support the message handler technique too.

**Comment by ewoutkramer** [comment]
An update from my side. I am reviewing the changes currently (yes, line by line ;-), and I like what I see so far. 

On the other side, I'd like to go further.  I understand Devereux-Henly has tried to stay as faithful as possible to the original FhirClient, but there's a number of things I'd like to change - if we are going to break interfaces, let's take the opportunity to look at other improvements too.

So, what I'd like to propose is
a) For me (and @brianpos)  to peer review the code as submitted in this PR
b) Pull it as a branche of develop, so we can continue working on it (and maybe integrate & discuss) the other changes I have in mind
c) Integrate it in develop for the New Orleans release (0.95) of the API, in februari.

Ideas? opinions?

**Comment by ewoutkramer** [comment]
Ok, so a) is done.  I just pulled PR #507 into a feature branch (480-httpclient), so we can work from there!  If any of the interested parties want to submit changes to the new FhirClient, pls base them on that branch!

**Comment by ewoutkramer** [comment]
Since the unit-tests for the client are disabled in the CI, did you run them manually, @Devereux-Henley ?

**Comment by Devereux-Henley** [comment]
@ewoutkramer Yes, I ran them manually.

**Comment by madhub** [comment]
when do you expect HttpClient support available in Fhir Client ?. 
It would be great if FhirClient or whatever new name you are choosing to take HttpClientHandler in the constructor so that unit testing & other aspects are easier .
```csharp

public class MyHttpClientHandler : HttpClientHandler
    {
        private static readonly HttpResponseMessage OkResponseMessage = new HttpResponseMessage(HttpStatusCode.OK);
        public MyHttpClientHandler(){}
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var content = request.Content;
            Console.WriteLine(content);
            // return simulted results here
            return Task.FromResult(OkResponseMessage);
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            HttpClient client = new HttpClient(handler: new MyHttpClientHandler());
            client.GetStringAsync("http://blah.uri");
            Console.ReadLine();
        }
    }

**Comment by brianpos** [comment]
I don't have a current timeline for it, if you wanted to try out the feature branch mentioned above and let us know if you have any suggestions or issues would be great.

**Comment by madhub** [comment]
Hi 
I will check out the feature branch.
Is their any way I the current release I can send the simulated results without hitting the HTTP endpoint.
This would be very useful for unit testing.

Thanks

**Comment by ewoutkramer** [comment]
Good questions - let's get this done - @madhub if you want to contribute, let's get this going.  I started to integrate this into an (I tink R4 branch) 480-httpclient.   I'd like to discuss my comment in this thread from 8 december 2017 - since this is a breaking change we can as well do some cleanup.  Which I have started on that branch.

**Comment by TechnikEmpire** [comment]
The premise of this ticket is entirely false, fyi. Have a look at the HttpClient implementations in corefx and mono for proof. TLS support is a target framework problem, not a HttpWebRequest problem.

**Comment by BradBarnich** [comment]
@ewoutkramer would you accept a PR for adding HttpClient to DSTU2/STU3? And do you prefer to keep both implementations? Rest.FhirClient (using HttpWebRequest) and Rest.Http.FhirClient (that uses HttpClient) like the R4 branch is using?

**Comment by ewoutkramer** [comment]
Well, we cannot drop the old version - that would break existing code. The original PR therefore uses another namespace.  It's just that I wanted to refactor a bit more. But I don't have time to do that, so maybe we should just pull the PR. @marcovisserFurore - opinions?

**Comment by brianpos** [comment]
I'm in two months on this one. 
I both want it,  and don't want to break.

**Comment by TechnikEmpire** [comment]
Someone call Microsoft and let them know that they forgot to put (Deprecated) over this object. This is sarcasm by the way. I guess no one read my comment. 11 months of people flopping around aimlessly working on something trying to solve a problem that doesn't exist. I'm unsubscribing from the thread don't worry. Carry on!

**Comment by brianpos** [comment]
There are more benefits than just TLS being considered here. The ability to hook things into the stream more easily is one of them, as I noted earlier in the t
Comment on testing handlers.

**Comment by BradBarnich** [comment]
Right. I personally have an interest for integration testing against our server in-memory, and adding retry for transient errors to our clients.

In fact, .net core's httpwebrequest is just a thin wrapper on httpclient: https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1106

**Comment by dnperfors** [comment]
Any progress on this issues? We want to use the api and want to test against an in-memory testserver as well.

**Comment by BradBarnich** [comment]
One of the major issues is that httpclient is async only, and FhirClient has both sync and async methods. There are some ways to do “sync over async” but they are prone to cause deadlocks in certain workloads

**Comment by wmrutten** [comment]
Async is preferred, but the API surface is not yet prepared for that; especially `IResourceResolver` is still synchronous. Encapsulating an internal async client could introduce deadlocks...

I would love to provide async resolvers, to prevent I/O calls from blocking. However because async is contageous, this would probably require converting large parts of the library to async (e.g. SnapshotGenerator, Validator). Maintaining compatibility to current synchronous logic would introduce a lot of code duplication. I haven't yet figured out an easy/feasible way to approach this.

**Comment by ewoutkramer** [comment]
@gstoian is working on it, based on @BradBarnich earlier work.  It's actually here: https://github.com/FirelyTeam/fhir-net-api/tree/feature/fhir-client-refactoring.  Also, he's splitting up the client into layers to separate pure-http handling from parsing from POCO handling to make it easier to test without having to spin up a test server.
