### ISSUE TITLE
The 'fhir_comments' feature is disabled

### ISSUE THREAD

**Issue by KelvinKaYiuLok** [FirelyTeam/fhir-net-api#901]
Hi,

I am using the Hl7.Fhir.STU3 v1.1.3 library for a project.

I tried the FhirClient class and have the PreferredFormat set to Json to get patient data from the http://hapi.fhir.org/baseDstu3 endpoint with criteria gender = male. Result The 'fhir_comments' feature is disabled

Doing the same search for gender = female was fine and I have also tried these endpoints https://data.developer.nhs.uk/ccri-fhir/STU3 and http://spark.kufu.no/fhir no issue.

I do need the PreferredFormat set to Json so that I can retrieve the raw Json string from the LastBodyAsText property via the FhirCient class.

Thanks for your help.

**Comment by mbaltus** [comment]
Hi Kelvin,

the fact that the other servers work correctly makes me think that there was an issue with the HAPI server. I've tried the search on that today, and get a good result, so I cannot reproduce your issue.

If you still encounter it, can you send me an email at fhirapi@fire.ly with the code you have written so I can take a look?

**Comment by KelvinKaYiuLok** [comment]
Thanks for the quick reply.
The below code will fail with the error I mentioned.

            var client = new FhirClient("http://hapi.fhir.org/baseDstu3");
            client.PreferredFormat = ResourceFormat.Json;
            var sp = new SearchParams();
            sp.Add("gender", "male");
            var result = client.Search<Patient>(sp);
            var moreResult = client.Continue(result); //Fail at this line

> Hi Kelvin,
> 
> the fact that the other servers work correctly makes me think that there was an issue with the HAPI server. I've tried the search on that today, and get a good result, so I cannot reproduce your issue.
> 
> If you still encounter it, can you send me an email at [fhirapi@fire.ly](mailto:fhirapi@fire.ly) with the code you have written so I can take a look?

**Comment by mbaltus** [comment]
Found the error. There's a Patient on that server, that has a "fhir_comments" section in the JSON, that was used to retain XML comments. This was removed from the specification (see http://www.healthintersections.com.au/?p=2569) and therefore the API will throw an error when it encounters that field. So basically there's nothing wrong with the API, but with the data on the HAPI server. I've tested and you can still create data on their server that translates the XML comments to a "fhir_comments" field in JSON, so that should be reported as a bug on the HAPI server or perhaps on the HAPI FHIR api.

You can create a workaround, by making the client parse the data more lenient:

`client.ParserSettings = new Hl7.Fhir.Serialization.ParserSettings() { PermissiveParsing = true };`

**Comment by KelvinKaYiuLok** [comment]
Thanks for your help and is all working now.
