### ISSUE TITLE
Support for Async processing request

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#929]
In R4 FHIR has included an option for Async requesting content from the FHIR server, which is primarily intended for use with the Bulk Data processing.
We should include support for this.
http://hl7.org/fhir/r4/async.html

**Comment by brianpos** [comment]
This will also need to update the prefer header handling, and also the acceptable status codes to include "202 Accepted"

**Comment by ewoutkramer** [comment]
Well, yes, but this spec is very drafty.  E.g. what would the response be?  For now, the only defined response is for Bulk Data, which returns a non-FHIR json file.  This will require quite some refactoring, since we are not prepared to accept anything that is not a FHIR resource yet.  So - yes, but also: this is not trivial I think.

**Comment by brianpos** [comment]
I'm working on this a bit, and wanted an issue to track it with.

**Comment by brianpos** [comment]
Also, there is no actual response to this call, just a location for the status tracking afterwards in the header. So the real change here was to support the other acceptable status outcomes.

**Comment by ewoutkramer** [comment]
Fixed by #996.
