### ISSUE TITLE
Support custom attributes in server reference response

### ISSUE THREAD

**Issue by rbaryolo** [FirelyTeam/fhir-net-api#960]
I am getting an R4 server response where references have an additional attribute `_id`, something like: `{practitioner: {_id: pract1, reference: Practitioner/pract1, id: pract1}}`. In this case the `HL7.Fhir.R4` library is throwing an exception because of the attribute. I wonder if there is any configuration to add to make the library to allow extra attributes, or any other solution at the library level, or maybe the library could add a new feature for this scenario.

**Comment by yosbeleg89** [comment]
I have the same issue, I tried adding `PermissiveParsing = true` and `AcceptUnknownMembers = true` to the `ParserSettings` it does not work either.

**Comment by ewoutkramer** [comment]
You can indeed add additional attributes non-FHIR attributes (using AcceptUnknownMembers), but they cannot start with an underscore ("_"), since the underscore is used in FHIR for keeping track of extensions and ids as described here: http://hl7.org/fhir/json.html#primitive - so it has a special meaning in the FHIR Json format - and the Json parser will always treat members starting with "_" as being objects.

The easy solution is not to use underscores and use AcceptUnknownMembers!.
