### ISSUE TITLE
Complex Extension does not roundtrip Poco - SourceNode - TypedElement

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/fhir-net-api#962]
See the unittest in branch fix/complexExtensionToSourceNode.

It complains with this error:

ExceptionNotification { Exception = Hl7.Fhir.ElementModel.StructuralTypeException: Type checking the data: Choice element 'valueExtension' is suffixed with unexpected type 'Extension', Message = "Type checking the data: Choice element 'valueExten"..., Severity = Error }

Maybe it is the wrong way of constructing a complex extension, but as demonstrated it is no problem to create this in a POCO.

**Comment by cknaap** [comment]
Update: The actual problem is the way the complex extension is built. AddExtension should not allow an element of type Extension as value.

**Comment by ewoutkramer** [comment]
Yes, indeed, this is no problem in the POCO, since there is no structural way you can express these kinds of constraints in a .NET typesystem.  Extension is a subclass of Element, so it will be allowed in the value element.

Making this into a structural solution would require generating a new subclass of Element of which Extension is not itself a subclass - and then having elements of the "*" type be of that specific subtype.  It's possible, but I am afraid we put too much stuff that is "profile validation" into the generated code, and also that we might encounter another axis or grouping to be turned into subclasses. And since C# only has one base class, I am very careful by solving this kind of problems by using inheritance....

I do not see why AddExtension should not work on Extensions? This is required for constructing nested extensions (e.g. complex extensions).

Your code fragment is indeed the correct way to do this.
